import { GraphicalTypeEnum } from './types'

export const cardList = [{
    name: 'Car Battery',
    description: 'Lorem ipsum dolor sit amet, consecte adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore.',
    id: 'did:web:api-rcs.susi.spherity.dev:did-registry:acme-power-drive-x-1000-3985-cb-1739186-d-8-d'
}]

export const dataFieldMap  = {
    id: { title: 'ID', type: GraphicalTypeEnum.NoRender },
    PPAP: { title: 'Production Part Approval Process', type: GraphicalTypeEnum.Panel },
    QAConfirmed: { title: 'QA Confirmed', type: GraphicalTypeEnum.Boolean },
    approvalDate: { title: 'Approval Date', type: GraphicalTypeEnum.Date },
    CTScans: { title: 'CT Scans', type: GraphicalTypeEnum.Panel, layout: { colSpan: 3 }},
    impurities: { title: 'Impurities', type: GraphicalTypeEnum.Text },
    anodeOverhang: { title: 'Anode Overhang', type: GraphicalTypeEnum.Text },
    batteryCellScan: { title: 'Battery Cell Scan', type: GraphicalTypeEnum.FileReport },
    scanDate: { title: 'Scan Date', type: GraphicalTypeEnum.Date },
    scanImage: { title: 'Scan Image', type: GraphicalTypeEnum.URL },
    scanTitle: { title: 'Scan Title', type: GraphicalTypeEnum.Text },
    scanImageSize: { title: 'Scan Image Size', type: GraphicalTypeEnum.Text },
    QARequirementsMet: { title: 'QA Requirements Met', type: GraphicalTypeEnum.Text },
    housingAndTheCathode: { title: 'Housing And The Cathode', type: GraphicalTypeEnum.FileReport },
    casingCathodeAndAnode: { title: 'Casing Cathode And Anode', type: GraphicalTypeEnum.FileReport },
    casingAndElectrodeAlignment: { title: 'Casing And Electrode Alignment', type: GraphicalTypeEnum.Text },
    batchUUID: { title: 'Batch UUID', type: GraphicalTypeEnum.NoRender },
    cellSampleUUID: { title: 'Cell Sample UUID', type: GraphicalTypeEnum.NoRender },
    performanceMetrics: { title: 'Performance Metrics', type: GraphicalTypeEnum.Panel, layout: { colSpan: 2 }},
    energyDensity: { title: 'Energy Density', type: GraphicalTypeEnum.Number },
    capacityRetention: { title: 'Capacity Retention', type: GraphicalTypeEnum.Text },
    chargeDischargeRate: { title: 'Charge Discharge Rate', type: GraphicalTypeEnum.Text },
    safetyDurabilityTests: { title: 'Safety Durability Tests', type: GraphicalTypeEnum.Panel, layout: { colSpan: 2 } },
    lifeCycle: { title: 'Life Cycle', type: GraphicalTypeEnum.Text },
    vibrationShock: { title: 'Vibration Shock', type: GraphicalTypeEnum.Text },
    shortCircuitResistance: { title: 'Short Circuit Resistance', type: GraphicalTypeEnum.Text },
    batteryCellHomologation: { title: 'Battery Cell Homologation', type: GraphicalTypeEnum.Panel, layout: { colSpan: 2 } },
    chargeRate: { title: 'Charge Rate', type: GraphicalTypeEnum.Text },
    lifeExpectancy: { title: 'Life Expectancy', type: GraphicalTypeEnum.Text },
    temperatureToleranceTests: { title: 'Temperature Tolerance Tests', type: GraphicalTypeEnum.Panel, layout: { colSpan: 2 } },
    operatingRange: { title: 'Operating Range', type: GraphicalTypeEnum.Text },
    thermalStability: { title: 'Thermal Stability', type: GraphicalTypeEnum.Text },
    coolingEfficiency: { title: 'Cooling Efficiency', type: GraphicalTypeEnum.Text },
    esgScore: { title: 'ESG Score', type: GraphicalTypeEnum.Number },
    location: { title: 'Location', type: GraphicalTypeEnum.Text },
    voltageMin: { title: 'Minimum Voltage', type: GraphicalTypeEnum.Number },
    batteryModel: { title: 'Battery Model', type: GraphicalTypeEnum.Text },
    manufacturer: { title: 'Manufacturer', type: GraphicalTypeEnum.Text },
    batteryWeight: { title: 'Battery Weight', type: GraphicalTypeEnum.Number },
    cellChemistry: { title: 'Cell Chemistry', type: GraphicalTypeEnum.Graph },
    materialFiles: { title: 'Material Files', type: GraphicalTypeEnum.File, layout: { colSpan: 2 }},
    supplyChainFiles: { title: 'Supply Chain Files', type: GraphicalTypeEnum.File, layout: { colSpan: 2 } },
    dueDiligenceScore: { title: 'Due Diligence Score', type: GraphicalTypeEnum.Number },
    expectedLifetimeKm: { title: 'Expected Lifetime (km)', type: GraphicalTypeEnum.Number },
    greenhouseGasScore: { title: 'Greenhouse Gas Score', type: GraphicalTypeEnum.Number },
    manufacturingPlace: { title: 'Manufacturing Place', type: GraphicalTypeEnum.Text },
    chemistryComposition: { title: 'Chemistry Composition', type: GraphicalTypeEnum.Text },
    tripEnergyEfficiency: { title: 'Trip Energy Efficiency', type: GraphicalTypeEnum.Number },
    expectedLifetimeMiles: { title: 'Expected Lifetime (miles)', type: GraphicalTypeEnum.Number },
    expectedLifetimeYears: { title: 'Expected Lifetime (years)', type: GraphicalTypeEnum.Number },
    maximumPowerPermitted: { title: 'Maximum Power Permitted', type: GraphicalTypeEnum.Number },
    cycleLifeReferenceTest: { title: 'Cycle Life Reference Test', type: GraphicalTypeEnum.Text },
    originalPowerCapability: { title: 'Original Power Capability', type: GraphicalTypeEnum.Number },
    temperatureIdleStateMax: { title: 'Maximum Idle Temperature', type: GraphicalTypeEnum.Number },
    temperatureIdleStateMin: { title: 'Minimum Idle Temperature', type: GraphicalTypeEnum.Number },
    commercialWarrantyPeriod: { title: 'Commercial Warranty Period', type: GraphicalTypeEnum.Number },
    initialDischargeCapacity: { title: 'Initial Discharge Capacity', type: GraphicalTypeEnum.Number },
    manufacturerIdentification: { title: 'Manufacturer Identification', type: GraphicalTypeEnum.Text },
    exhaustionCapacityThreshold: { title: 'Exhaustion Capacity Threshold', type: GraphicalTypeEnum.Number },
} as const
