
export const cardList = [{
    name: 'Car Battery',
    description: 'Lorem ipsum dolor sit amet, consecte adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore.',
    id: 'did:web:api-rcs.susi.spherity.dev:did-registry:acme-power-drive-x-1000-3985-cb-1739186-d-8-d'
}]

export enum GraphicalTypeEnum {
    Panel = 'Panel',
    Boolean = 'Boolean',
    NoRender = 'NoRender',
    Graph = 'Graph',
    Number = 'Number',
    Text = 'Text',
    Date = 'Date',
    File = 'File',
    FileReport = 'FileReport',
    URL = 'URL'
}

export const dataFieldMap  = {
    id: { title: 'ID', type: GraphicalTypeEnum.NoRender },
    PPAP: { title: 'Production Part Approval Process', type: GraphicalTypeEnum.Panel, layout: { colSpan: 1 } },
    QAConfirmed: { title: 'QA Confirmed', type: GraphicalTypeEnum.Boolean, layout: { icon: 'check' } },
    approvalDate: { title: 'Approval Date', type: GraphicalTypeEnum.Date, layout: { icon: 'calendar-days' } },
    CTScans: { title: 'CT Scans', type: GraphicalTypeEnum.Panel, layout: { colSpan: 4 } },
    impurities: { title: 'Impurities', type: GraphicalTypeEnum.Text, layout: { icon: 'exclamation-circle' } },
    anodeOverhang: { title: 'Anode Overhang', type: GraphicalTypeEnum.Text, layout: { icon: 'minus-circle' } },
    batteryCellScan: { title: 'Battery Cell Scan', type: GraphicalTypeEnum.FileReport },
    scanDate: { title: 'Scan Date', type: GraphicalTypeEnum.Date },
    scanImage: { title: 'Scan Image', type: GraphicalTypeEnum.URL },
    scanTitle: { title: 'Scan Title', type: GraphicalTypeEnum.Text },
    scanImageSize: { title: 'Scan Image Size', type: GraphicalTypeEnum.Text },
    QARequirementsMet: { title: 'QA Requirements Met', type: GraphicalTypeEnum.Text },
    housingAndTheCathode: { title: 'Housing And The Cathode', type: GraphicalTypeEnum.FileReport },
    casingCathodeAndAnode: { title: 'Casing Cathode And Anode', type: GraphicalTypeEnum.FileReport },
    casingAndElectrodeAlignment: { title: 'Casing And Electrode Alignment', type: GraphicalTypeEnum.Text, layout: { icon: 'clipboard-document-check' } },
    batchUUID: { title: 'Batch UUID', type: GraphicalTypeEnum.NoRender },
    cellSampleUUID: { title: 'Cell Sample UUID', type: GraphicalTypeEnum.NoRender },
    performanceMetrics: { title: 'Performance Metrics', type: GraphicalTypeEnum.Panel, layout: { colSpan: 2 } },
    energyDensity: { title: 'Energy Density', type: GraphicalTypeEnum.Number, layout: { icon: 'bolt' } },
    capacityRetention: { title: 'Capacity Retention', type: GraphicalTypeEnum.Text, layout: { icon: 'battery-100' } },
    chargeDischargeRate: { title: 'Charge Discharge Rate', type: GraphicalTypeEnum.Text, layout: { icon: 'battery-50' } },
    safetyDurabilityTests: { title: 'Safety Durability Tests', type: GraphicalTypeEnum.Panel, layout: { colSpan: 2 } },
    lifeCycle: { title: 'Life Cycle', type: GraphicalTypeEnum.Text, layout: { icon: 'arrow-path' } },
    vibrationShock: { title: 'Vibration Shock', type: GraphicalTypeEnum.Text, layout: { icon: 'fire' } },
    shortCircuitResistance: { title: 'Short Circuit Resistance', type: GraphicalTypeEnum.Text, layout: { icon: 'chip' } },
    batteryCellHomologation: { title: 'Battery Cell Homologation', type: GraphicalTypeEnum.Panel, layout: { colSpan: 2 } },
    chargeRate: { title: 'Charge Rate', type: GraphicalTypeEnum.Text, layout: { icon: 'battery-0'} },
    lifeExpectancy: { title: 'Life Expectancy', type: GraphicalTypeEnum.Text, layout: { icon: 'clock' } },
    temperatureToleranceTests: { title: 'Temperature Tolerance Tests', type: GraphicalTypeEnum.Panel, layout: { colSpan: 2 } },
    operatingRange: { title: 'Operating Range', type: GraphicalTypeEnum.Text, layout: { icon: 'globe' } },
    thermalStability: { title: 'Thermal Stability', type: GraphicalTypeEnum.Text, layout: { icon: 'temperature' } },
    coolingEfficiency: { title: 'Cooling Efficiency', type: GraphicalTypeEnum.Text, layout: { icon: 'cold' } },
    esgScore: { title: 'ESG Score', type: GraphicalTypeEnum.Number, layout: { icon: 'leaf' } },
    location: { title: 'Location', type: GraphicalTypeEnum.Text, layout: { icon: 'map-pin' } },
    voltageMin: { title: 'Minimum Voltage', type: GraphicalTypeEnum.Number, layout: { icon: 'bolt' } },
    batteryModel: { title: 'Battery Model', type: GraphicalTypeEnum.Text, layout: { icon: 'battery-100'} },
    manufacturer: { title: 'Manufacturer', type: GraphicalTypeEnum.Text, layout: { icon: 'chip'} },
    batteryWeight: { title: 'Battery Weight', type: GraphicalTypeEnum.Number, layout: { icon: 'weight'} },
    cellChemistry: { title: 'Cell Chemistry', type: GraphicalTypeEnum.Graph, layout: { colSpan: 4 } },
    materialFiles: { title: 'Material Files', type: GraphicalTypeEnum.File, layout: { colSpan: 2 } },
    supplyChainFiles: { title: 'Supply Chain Files', type: GraphicalTypeEnum.File, layout: { colSpan: 2 } },
    dueDiligenceScore: { title: 'Due Diligence Score', type: GraphicalTypeEnum.Number, layout: { icon: 'clipboard-document-check'} },
    expectedLifetimeKm: { title: 'Expected Lifetime (km)', type: GraphicalTypeEnum.Number, layout: { icon: 'clock' } },
    greenhouseGasScore: { title: 'Greenhouse Gas Score', type: GraphicalTypeEnum.Number, layout: { icon: 'co2' } },
    manufacturingPlace: { title: 'Manufacturing Place', type: GraphicalTypeEnum.Text, layout: { icon: 'location-pin'} },
    chemistryComposition: { title: 'Chemistry Composition', type: GraphicalTypeEnum.Text, layout: { icon: 'beaker' } },
    tripEnergyEfficiency: { title: 'Trip Energy Efficiency', type: GraphicalTypeEnum.Number, layout: { icon: 'chart-bar' } },
    expectedLifetimeMiles: { title: 'Expected Lifetime (miles)', type: GraphicalTypeEnum.Number, layout: { icon: 'road' } },
    expectedLifetimeYears: { title: 'Expected Lifetime (years)', type: GraphicalTypeEnum.Number, layout: { icon: 'clock' } },
    maximumPowerPermitted: { title: 'Maximum Power Permitted', type: GraphicalTypeEnum.Number, layout: { icon: 'bolt' } },
    cycleLifeReferenceTest: { title: 'Cycle Life Reference Test', type: GraphicalTypeEnum.Text, layout: { icon: 'arrow-path' } },
    originalPowerCapability: { title: 'Original Power Capability', type: GraphicalTypeEnum.Number, layout: { icon: 'bolt' } },
    temperatureIdleStateMax: { title: 'Maximum Idle Temperature', type: GraphicalTypeEnum.Number, layout: { icon: 'temperature' } },
    temperatureIdleStateMin: { title: 'Minimum Idle Temperature', type: GraphicalTypeEnum.Number, layout: { icon: 'cold' } },
    commercialWarrantyPeriod: { title: 'Commercial Warranty Period', type: GraphicalTypeEnum.Number, layout: { icon: 'shield-check' } },
    initialDischargeCapacity: { title: 'Initial Discharge Capacity', type: GraphicalTypeEnum.Number, layout: { icon: 'battery-50' } },
    manufacturerIdentification: { title: 'Manufacturer Identification', type: GraphicalTypeEnum.Text, layout: { icon: 'fingerprint'} },
    exhaustionCapacityThreshold: { title: 'Exhaustion Capacity Threshold', type: GraphicalTypeEnum.Number, layout: { icon: 'battery-error' } },
} as const
